import { LanguageCode, QueryResponse } from "./types";

const USE_MOCK_DATA = false; // Mock data is disabled for the real integration test

export async function queryVoice(
  audioBlob: Blob,
  language: LanguageCode
): Promise<QueryResponse> {
  if (USE_MOCK_DATA) {
    return getMockResponse(language);
  }

  const formData = new FormData();
  formData.append("audio_data", audioBlob, "recording.wav");
  formData.append("language", language);

  const response = await fetch("/api/query", {
    method: "POST",
    body: formData,
  });

  if (!response.ok) {
    throw new Error(`API Error: ${response.statusText}`);
  }

  return response.json();
}

function getMockResponse(language: string): Promise<QueryResponse> {
  return new Promise((resolve) => {
    setTimeout(() => {
      resolve({
        request_id: "demo-request-" + Date.now(),
        language: language,
        transcript: "This is a simulated transcript from the mock data layer.",
        detected_lang: language + "-IN",
        answer: "This is a simulated answer generated by the mocked backend for development purposes. It proves the UI can parse the QueryResponse schema correctly.",
        answer_source: "llm",
        retrieved_chunks: [
          { strategy: "P", language: language, text: "Simulated passage chunk containing relevant context 1." },
          { strategy: "SM", language: language, text: "Simulated semantic chunk containing relevant context 2." },
          { strategy: "H", language: language, text: "Simulated hybrid chunk containing relevant context 3." }
        ],
        latency_breakdown: {
          stt_ms: 61,
          embedding_ms: 5,
          retrieval_ms: 41,
          rerank_ms: 2,
          off_topic_ms: 2,
          generation_ms: 51,
          grounding_ms: 2,
          total_ms: 164
        },
        guardrail: {
          blocked: false,
          reason: null,
          grounded: true
        },
        model: "openai/gpt-oss-20b"
      });
    }, 1500); // Simulate network/processing latency
  });
}
